services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    image: app:vend-sell
    container_name: vend-sell
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000