# docker-compose.yml

services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: vend_db

volumes:
  db_data:
  
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    image: app:vend-sell
    container_name: vend-sell
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["./start.sh"]
    # OR override command entirely
    # command: uvicorn main:app --host 0.0.0.0 --port 8000
