# docker-compose.yml

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    image: app:vend-sell
    container_name: vend-sell
    # Override the default start.sh if needed
    entrypoint: ["./start.sh"]
    # OR override command entirely
    # command: uvicorn main:app --host 0.0.0.0 --port 8000
