"""added shop category

Revision ID: 4de5be92bf2b
Revises: 6de0da34211c
Create Date: 2025-08-11 14:09:55.143621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4de5be92bf2b'
down_revision: Union[str, Sequence[str], None] = '6de0da34211c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('shop_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'shop_categories')
    
    # ### end Alembic commands ###
