"""update user table

Revision ID: 5e585c5316c2
Revises: 4de5be92bf2b
Create Date: 2025-10-06 18:04:41.149411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e585c5316c2'
down_revision: Union[str, Sequence[str], None] = '4de5be92bf2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendoruser', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('vendoruser', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendoruser', 'reset_token_expires')
    op.drop_column('vendoruser', 'password_reset_token')
    # ### end Alembic commands ###
