"""geloactaion_migrate

Revision ID: d30f6ef88d31
Revises: 
Create Date: 2025-08-07 13:49:11.161617

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30f6ef88d31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_locations_location', 'locations', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_location', table_name='locations', postgresql_using='gist')
    op.drop_column('locations', 'location')
    # ### end Alembic commands ###
